### ISSUE TITLE
Update the java version

### ISSUE THREAD

**Issue by shelltar** [Fullaxx/biglybt-extreme#10]
Java 17 is no longer supported. The latest mod require Java 21, otherwise this error will occur in the Tracker Status:

```
Connection Error ('boolean sun.net.www.http.HttpClient.parseHTTP(sun.net.www.MessageHeader, sun.net.www.protocol.http.HttpURLConnection)')
```

**Comment by Fullaxx** [comment]
Where do you see those errors? Is that in a log file or in the GUI?
Can you post a screenshot?

**Comment by shelltar** [comment]
In the GUI, it's a message in the Tracker Status column. Unfortunately, I can't make a screenshot now, because I made a "dirty" fix in my fork. It works fine with Java 21.

**Comment by Fullaxx** [comment]
I was going to revert to 3.3.0.0 b/c ubuntu doesn't support Java 21 in their repository, but saw the official java repo and I will kindly rip off your solution for installing Java 21. More to follow, thanks!

**Comment by Fullaxx** [comment]
Thanks for tracking this, I added you to the contributors list!
