### ISSUE TITLE
Client Files

### ISSUE THREAD

**Issue by AllanHBC** [Fullaxx/biglybt-extreme#14]
Hello! How can I add Client Files to the container? There are new simulation versions for other Torrent Clients, and I would like to make use of them.

**Comment by Fullaxx** [comment]
Can you be more specific? What do you mean by "Client Files" and what do you mean by "simulation versions"?

**Comment by AllanHBC** [comment]
Sure!
On BiglyBT > Tools > Options > Extreme Mod > Perfect Spoof > This list
