### ISSUE TITLE
Container always reinstall from scratch on each reboot

### ISSUE THREAD

**Issue by nobodyondocker** [Fullaxx/biglybt-extreme#2]
Hello Fullaxx, 

It's been several hours now that I try to make your dockers work, unfortunately, without success. 

Here's my problem: The initial installation well, I manage to map the /data and /root/.bigybt folders without problems, the docker starts the installation and everything works. 

However, if I close or restart the container, the installation starts again from scratch and the end, biglybt does not start again. 

I noticed that if I don't put the folder persistent, the installation works, but I lose all the configurations every time. 

I tried to do the test with a non-root user "guest", in this case, the installation starts again, but it finishes and I have the configurations I made, but impossible to launch a download, as if the user did not have access to the backend of bigly... 

In any case, I checked the rights on the different folders and they are indeed root:root when I test in root and 200:2000 and I test in root.

The is the stack:

 torrent:
    image: fullaxx/biglybt-extreme:3.3.0.0
    container_name: BiglyBT
    environment:
      - PUID=2000
      - PGID=2000
      - UMASK=002
      - TZ=America/New_York
      - VNCRES=1920x1080
      - VNCUSER=guest
      - VNCUID=2000
      - VNCGROUP=guests
      - VNCGID=2000
      - VNCPASS=Extreme
    volumes:
      - /DATA/AppData/BiglyBT/bbtconfig:/home/guest/.biglybt
      - /mnt/HDD/DATA_HDD/BiglyBT/data:/data
    restart: always

There is the log of the container:
 * Setting up X socket directories...
   ...done.
 * Starting system message bus dbus
   ...done.
useradd: warning: the home directory /home/guest already exists.
useradd: Not copying any file from skel directory into it.
/usr/bin/xauth:  file /home/guest/.Xauthority does not exist
New Xtigervnc server 'df594af302fc:1 (guest)' on port 5901 for display :1.
Use xtigervncviewer -SecurityTypes VncAuth,TLSVnc -passwd /home/guest/.vnc/passwd df594af302fc:1 to connect to the VNC server.

Your help will be very appreciated!

Thank you!

**Comment by Fullaxx** [comment]
What are you using to manipulate your containers? docker-compose? portainer?
If you are using docker-compose "up" and "down" this is the intended behavior.
If you are "stopping" and "starting" the stack, this is the intended behavior.

It looks like your container in being removed instead of being restarted.
The BiglyBT Software is not installed in the Dockerfile.
When a new container is spawned the autostart script will install the BiglyBT software.
When a container is properly restarted, that installation will persist, 
but when a container is removed and re-created, the software will once again install in that new container.

You can see that behavior with the following commands:
docker run -d --name bbtex -p 127.0.0.1:5901:5901 fullaxx/biglybt-extreme:3.3.0.0
docker restart bbtex
This will restart the existing container w/o reinstall.

If you use these commands, you will see the reinstall:
docker run -d --name bbtex -p 127.0.0.1:5901:5901 fullaxx/biglybt-extreme:3.3.0.0
docker rm bbtex
docker run -d --name bbtex -p 127.0.0.1:5901:5901 fullaxx/biglybt-extreme:3.3.0.0

**Comment by nobodyondocker** [comment]
Hello Fullaxx, thank you for the quick feedback, it's appreciated!

It is indeed the conclusion that I had made after my many tests, that when you stop or update a stack, the containers were pull again. 

However, unlike all the other containers to which I add a persistent folder for their configurations and data and which start as if they had never been deleted, the BiglyBT application does not launch at the end of the installation as shown (Capture #1) (Container log Capture #2). 

But if I remove the persistent folder "- /DATA/AppData/BiglyBT/bbtconfig:/root/.biglybt", the reinstallation ends normally (Capture #3), but I lose all the configurations with each stack update, which is not viable. 

Is it me who does not understand well, do we have to make a particular command to launch the software by VNC afterwards? 

The reason why I stack it with Portainer is that I use a NordLynx container for the connection and dependency on the "vpn" service. 

Other containers work normally under this configuration. 

I attach the screenshots and my docker-compose with two or three less info. 

The only thing that I think is maybe that the new root doesn't have the same ID or something like that, that block the access to the config folder. But, when I try with this code following, the container start after it's "refresh install", but it's like that the guest account doen't have access to the BiglyBT backend, the download doesn't start, the xmwebui can't show what is in the "download list", etc.:
torrent:
image: fullaxx/biglybt-extreme:3.3.0.0
container_name: BiglyBT
environment:
- PUID=2000
- PGID=2000
- UMASK=002
- TZ=America/New_York
- VNCRES=1920x1080
- VNCUSER=guest
- VNCUID=2000
- VNCGROUP=guests
- VNCGID=2000
- VNCPASS=Extreme
volumes:
- /DATA/AppData/BiglyBT/bbtconfig:/home/guest/.biglybt
- /mnt/HDD/DATA_HDD/BiglyBT/data:/data
restart: always

Seem to be some rights problems, but I'm unable to figure how to fix them...

Your help is welcome. 

Thanks in advance!

Capture#1
![Capture#1](https://user-images.githubusercontent.com/72503977/231013706-393da58c-d0f0-4345-876e-04cb0d4df3ff.png)
Capture #2
![Capture#2](https://user-images.githubusercontent.com/72503977/231013696-5e4e7895-af87-4342-b52f-1c8d8f63d1e6.png)
Capture #3
![Capture#3](https://user-images.githubusercontent.com/72503977/231013700-81552183-dbe6-4bc2-a063-d9903e81f36b.png)
[docker compose.txt](https://github.com/Fullaxx/biglybt-extreme/files/11194568/docker.compose.txt)

**Comment by Fullaxx** [comment]
I will try to re-create your issue tomorrow, hopefully I can find a real solution.

In the mean time, could you provide the output of the BiglyBT log file?
If you open an xterm and type cat /opt/biglybt/biglybt.log
See LogImage:
![log](https://user-images.githubusercontent.com/4896172/231030195-a2759fb1-a9ca-471d-ad04-ba646fe61740.jpg)

Also try this and tell me if this works:
When BiglyBT fails to launch automatically, can you then launch it manually?
By opening an xterm and typing
```shell
/app/scripts/biglybt.sh
```

Does that work?

**Comment by nobodyondocker** [comment]
Hope that this screenshots will help you to figure why it's not work!
Thank you for fast anwser and have a nice day!

Root + xterm script that can't start BiglyBT
![Root + xterm script that can't start BiglyBT](https://user-images.githubusercontent.com/72503977/231042315-dd3e3b80-b4b4-4145-9aad-0dce71521ce8.png)

Guest with start of BiglyBT, but nothing start I the torrent list...
![Guest with start of BiglyBT](https://user-images.githubusercontent.com/72503977/231042320-99405b12-0b89-4587-9243-78a4eaaa4aae.png)

**Comment by Fullaxx** [comment]
Well, I do see a problem:
/opt/biglybt/biglybt: line 109: Error: command not found
/opt/biglybt/biglybt: line 110: Cannot: command not found
I have not idea what that is, or how that could be happening.
I have never seen that before.
It almost looks like something is changing your biglybt installation?

I added some extra error checking to help debug
Would you try this for me:
1) docker pull fullaxx/biglybt-extreme

Launch a new container from command line:
2) docker run -d --name bbtex -p 5901:5901 -e
TZ=America/New_York -e VNCRES=1920x1080 -e VNCPASS=Extreme -e
VNCUSER=guest -e VNCUID=2000 -e VNCGROUP=guests -e VNCGID=2000 -v
/DATA/AppData/BiglyBT/bbtconfig:/home/guest/.biglybt -v
/mnt/HDD/DATA_HDD/BiglyBT/data:/data fullaxx/biglybt-extreme

Let it install and startup, then quit Bigly:
![exit_biglybt](https://user-images.githubusercontent.com/4896172/231132284-1a291ee5-ddab-4a9a-818f-5e1b4bc2ec46.jpg)

Then exit Openbox:
![exit_docker_image](https://user-images.githubusercontent.com/4896172/231132430-5313f64d-3a77-43af-9a02-2ad17ed3932c.jpg)

Then restart your container:
3) docker start bbtex

This works on my machine, does it work on yours?
If it still fails, please provide the output from docker logs bbtex
and the output from cat /opt/biglybt/biglybt.log

**Comment by nobodyondocker** [comment]
Hi Fullaxx,

When I use your code and that I restart the container, it's not reinstall from scratch like you said, but, when I use the "guest" account, impossible to start download. The torrent is there in waiting, but nothing append and some plugins are not shows.

If I try in root without "guest..ing", it's download, and it's start when I reboot. 

When I try to check the cat /opt/biglybt/biglybt.log with the "guest" account, this is the results:
![P1](https://user-images.githubusercontent.com/72503977/231165099-90524a41-a6b1-4c60-98af-3bb3deae997b.png)
![P2](https://user-images.githubusercontent.com/72503977/231165134-d20831f0-1338-45eb-bb67-8af3eb41a5bf.png)
![P3](https://user-images.githubusercontent.com/72503977/231165145-5a7569d8-7a4c-44fa-935e-3d23fc650f72.png)

When I try to "update" or "redeploy" the root container, the same error append that the last post appear or by stack update deploy:
![docker rm](https://user-images.githubusercontent.com/72503977/231221124-810d9a6c-4f01-41e0-855d-e5a2046127c2.png)

So, I'm partially fonctionnal, but I prefer to use a stack to link all the container needed for download and easelly update it. 

If I need to use the cli, I can use it, but if I need to clear all persistantes datas and redone all of the config on each new version... I will, but it's not perfect.... 

If a another way to achieve that is needed, I'm open!

Thank for your help!

**Comment by Fullaxx** [comment]
Thank you for your help. I believe I found the bug you were experiencing #4
Please test the latest image. It should be working now.

**Comment by nobodyondocker** [comment]
I will try it!
Thank for your help.
Do you think that I can use it now in a stack?
The webui plugin will be disponible fir the non root user?
Thank you!

**Comment by Fullaxx** [comment]
Yes, that is the plan.
And yes the plugins should be working also.

**Comment by nobodyondocker** [comment]
Hi Fullaxx!

- Good new: The guest account work perfectly fine like when I use the root account, so this bug is corrected.
- Bad new: When I rm the container, or that I stop and start in a stack, it's make the same error like when I'm in root. Sadly, doesnt seem to have more informations despite of your modifications for more verbose. Always with persistant data for configurations... It's like the installer saw a specific file and it's doesn't fit with it's sequence, I don't understand...

The manual command doesn't work too...
![2023-04-11 15_23_38-192 168 2 25_5901 (cb099c9ec100_1 (guest)) - VNC Viewer](https://user-images.githubusercontent.com/72503977/231310604-409815d5-1657-4602-a5b8-f2588031286a.png)

Thank you!

**Comment by Fullaxx** [comment]
wow, Thanks for the tip, I would have never seen that one.
Please pull latest and See #6

**Comment by nobodyondocker** [comment]
Seem to work A1, your are the best!

Thank you for your fast responses in the resolving of my problem, I appreciate it!

**Comment by Fullaxx** [comment]
Welcome, I'm glad you find this useful!
