### ISSUE TITLE
java.vmoptions not retaining changes

### ISSUE THREAD

**Issue by shelltar** [Fullaxx/biglybt-extreme#7]
The '/root/.biglybt/java.vmoptions' file gets overwritten with each installation. When I update the container, I need to reconfigure the RAM limit in the biglybt settings.

**Comment by Fullaxx** [comment]
Thanks for the issue. Originally it was necessary to remove that file so the installer would work. I have added more conditional logic so that we don't modify the file more than once. Please test the 'donotremovejavavmoptions' branch if you can, otherwise I will merge soon after more testing.

**Comment by shelltar** [comment]
Apologies for the late reply. I have just tested it, and it seems to be working as expected. Could you also include Asian fonts in the installer to ensure that the torrent titles are displayed correctly?

```
apt install -y fonts-arphic-ukai fonts-arphic-uming fonts-ipafont-mincho fonts-ipafont-gothic fonts-unfonts-core
```

**Comment by Fullaxx** [comment]
done, thanks for the reminder, I lost track of the asian font request.
